name: mi_tienda_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  supabase_flutter: ^1.10.11
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3  # ✅ Solo aquí

flutter_launcher_icons:            # ✅ Configuración separada
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/icon.png

dependency_overrides:
  sign_in_with_apple: ^7.0.1
